# Generated by Django 2.2.3 on 2019-08-23 17:26

from django.db import migrations, models
import zazi.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'BANNED'), (0, 'REQUESTED_MEMBERSHIP'), (1, 'VERIFIED'), (2, 'APPROVED')], null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_id',
            field=models.CharField(default=zazi.core.utils.generate_id, max_length=100, unique=True),
        ),
    ]
