# Generated by Django 2.2.3 on 2019-12-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zazi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190823_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMINISTRATOR'), (2, 'LOANEE')], null=True),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('invitation_code', models.CharField(default=zazi.apps.users.models.get_invitation_code, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('phone_number', 'invitation_code')},
            },
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_pin', models.CharField(max_length=250)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authentication_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_authentication',
            },
        ),
    ]
