# Generated by Django 2.2.3 on 2019-12-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191219_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserAccount'),
        ),
    ]
