# Generated by Django 2.2.3 on 2019-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinvitation_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
