# Generated by Django 2.2.3 on 2019-12-20 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191220_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_authentication', to=settings.AUTH_USER_MODEL),
        ),
    ]
