# Generated by Django 2.2.3 on 2019-12-22 13:56

from django.db import migrations, models
import zazi.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191220_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='invitation_id',
            field=models.CharField(default=zazi.core.utils.generate_id, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='sms_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
