# Generated by Django 2.2.3 on 2020-01-16 19:17

from django.db import migrations, models
import zazi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinvitation_invitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='invitation_id',
            field=models.CharField(default=zazi.apps.users.models.get_invitation_id, max_length=50, null=True),
        ),
    ]
