# Generated by Django 2.2.3 on 2020-02-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200116_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.UserAccount'),
        ),
    ]
