# Generated by Django 2.2.3 on 2020-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200218_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='security_pin',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
