# Generated by Django 2.2.3 on 2020-03-21 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zazi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20200309_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPINCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_id', models.CharField(default=zazi.apps.users.models.get_reset_id, max_length=50, null=True)),
                ('reset_code', models.CharField(default=zazi.apps.users.models.get_reset_code, max_length=6)),
                ('reset_on', models.DateTimeField(null=True)),
                ('expires', models.DateTimeField(null=True)),
                ('requested_on', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_change_requests', to=settings.AUTH_USER_MODEL)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
