# Generated by Django 3.0.4 on 2020-03-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpesa', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaLoanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='loan.LoanTransaction')),
                ('mpesa_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_transactions', to='mpesa.MpesaTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MpesaLoanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_products', to='loan.LoanProduct')),
                ('mpesa_api_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='mpesa.MpesaAPIAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MpesaLoanAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='loan.LoanAccount')),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='mpesa.MpesaAccount')),
            ],
            options={
                'unique_together': {('loan_account', 'mpesa_account')},
            },
        ),
    ]
