# Generated by Django 3.0.4 on 2020-03-29 09:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import zazi.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('general_ledger', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFundSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_source_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fund_sources', to='banking.BankAccount')),
            ],
            options={
                'db_table': 'loan_fund_source',
            },
        ),
        migrations.CreateModel(
            name='LoanLedgerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('ledger_code', models.CharField(max_length=50, unique=True)),
                ('account_category', models.PositiveSmallIntegerField(choices=[(1, 'ASSET'), (2, 'LIABILITY'), (3, 'CAPITAL'), (4, 'REVENUE'), (5, 'EXPENSE')], null=True)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'LOAN_FUND_SOURCE'), (2, 'LOAN_PORTFOLIO'), (3, 'LOAN_LIABILITIES'), (4, 'INTEREST_RECEIVABLE'), (5, 'FEES_RECEIVABLE'), (6, 'PENALTIES_RECEIVABLE'), (7, 'INTEREST_REVENUE'), (8, 'PENALTIES_REVENUE'), (9, 'FEES_REVENUE'), (10, 'PRINCIPAL_WRITE_OFF_EXPENSE'), (11, 'INTEREST_WRITE_OFF_EXPENSE'), (12, 'PENALTIES_WRITE_OFF_EXPENSE'), (13, 'FEES_WRITE_OFF_EXPENSE'), (14, 'TRANSACTION_FEES_EXPENSE'), (15, 'OWNERS_EQUITY')])),
                ('is_contra', models.NullBooleanField()),
            ],
            options={
                'db_table': 'loan_ledger_account',
                'ordering': ['ledger_code'],
            },
        ),
        migrations.CreateModel(
            name='OwnersCapitalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('notes', models.CharField(max_length=200)),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT')])),
                ('entry_date', models.DateTimeField(null=True)),
                ('loan_ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_equity_entries', to='loan_ledger.LoanLedgerAccount')),
            ],
            options={
                'db_table': 'loan_owners_capital_entry',
            },
        ),
        migrations.CreateModel(
            name='LoanTransactionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT')])),
                ('entry_date', models.DateTimeField(null=True)),
                ('ledger_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_ledger.LoanLedgerAccount')),
                ('loan_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.LoanTransaction')),
            ],
            options={
                'db_table': 'loan_transaction_entry',
            },
        ),
        migrations.CreateModel(
            name='LoanLedgerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('loan_fund_source_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_portfolio_credit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_portfolio_debit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_receivable_debit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_receivable_credit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_receivable_debit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_receivable_credit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_receivable_debit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_receivable_credit_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_liabilities_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('owners_equity_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_revenue_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_revenue_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_revenue_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('principal_write_off_expense_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_write_off_expense_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_write_off_expense_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_write_off_expense_balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_fund_source_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_portfolio_credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_portfolio_debit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_receivable_debit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_receivable_credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_receivable_debit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_receivable_credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_receivable_debit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_receivable_credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('loan_liabilities_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('owners_equity_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_revenue_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_revenue_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_revenue_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('principal_write_off_expense_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('interest_write_off_expense_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('penalties_write_off_expense_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('fees_write_off_expense_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('balance_as_at', models.DateTimeField(null=True)),
                ('is_current', models.NullBooleanField()),
                ('previous_balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_ledger.LoanLedgerBalance')),
            ],
            options={
                'db_table': 'loan_ledger_balance',
                'ordering': ['balance_as_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanLedgerAccountingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_ledger.GLAccount')),
                ('loan_ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_links', to='loan_ledger.LoanLedgerAccount')),
            ],
            options={
                'db_table': 'loan_ledger_accounting_link',
                'ordering': ['loan_ledger_account__ledger_code'],
            },
        ),
        migrations.CreateModel(
            name='LoanFundSourceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18)),
                ('notes', models.CharField(max_length=200)),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT')])),
                ('entry_date', models.DateTimeField(null=True)),
                ('fund_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_ledger.LoanFundSource')),
            ],
            options={
                'db_table': 'loan_fund_source_entry',
            },
        ),
        migrations.AddField(
            model_name='loanfundsource',
            name='loan_ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fund_source', to='loan_ledger.LoanLedgerAccount'),
        ),
    ]
