# Generated by Django 3.0.4 on 2020-03-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default', models.BooleanField(default=False)),
                ('service_provider', models.IntegerField(choices=[(1, "Africa's Talking"), (2, 'Express SMS')], null=True)),
                ('api_key', models.CharField(help_text="For Africas' Talking, this is the username", max_length=100)),
                ('api_secret', models.CharField(help_text="For Africas' Talking, this is the api key", max_length=100)),
                ('is_sandbox', models.NullBooleanField()),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'SMS IN'), (2, 'SMS OUT')])),
                ('message', models.CharField(max_length=480)),
                ('sender_id', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=50, null=True)),
                ('recipient_id', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Error')], null=True)),
                ('delivered', models.NullBooleanField()),
                ('time_delivered', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sms_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SMSGateway')),
            ],
        ),
    ]
