# Generated by Django 3.0.4 on 2020-03-29 09:35

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import zazi.core.json
import zazi.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='bank/logos')),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('bank_account_id', models.CharField(default=zazi.core.utils.generate_id, max_length=25)),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('balance_items', django.contrib.postgres.fields.jsonb.JSONField(encoder=zazi.core.json.JSONEncoder, null=True)),
                ('bank_account_type', models.PositiveSmallIntegerField(choices=[(1, 'MOBILE_MONEY_ACCOUNT'), (2, 'BANK_ACCOUNT'), (3, 'SAVINGS_ACCOUNT'), (4, 'LOAN_ACCOUNT')], null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.Bank')),
                ('gl_ledger_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_ledger.GLAccount')),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='BankingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'DEPOSIT'), (2, 'WITHDRAW'), (3, 'TRANSFER')])),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'PENDING_PROCESSING_APPROVAL'), (1, 'PENDING_PROCESSING'), (3, 'COMPLETED_PROCESSING'), (2, 'FAILED_PROCESSING'), (4, 'PENDING_POSTING_TO_LEDGER'), (5, 'POSTED_TO_LEDGER'), (6, 'CANCELLED'), (7, 'FLAGGED')])),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.BankAccount')),
            ],
            options={
                'db_table': 'bank_transaction',
            },
        ),
        migrations.CreateModel(
            name='BankingTransactionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT')])),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.BankAccount')),
                ('banking_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.BankingTransaction')),
            ],
            options={
                'db_table': 'bank_transaction_entry',
            },
        ),
    ]
