# Generated by Django 3.0.4 on 2020-03-29 09:35

from django.db import migrations, models
import django.db.models.deletion
import zazi.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpesa', '0001_initial'),
        ('users', '0015_resetpincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_id', models.CharField(default=zazi.core.utils.generate_id, max_length=100)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=150, null=True)),
                ('identity_type', models.PositiveSmallIntegerField(choices=[(1, 'PERSON'), (2, 'BUSINESS')], null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED')], null=True)),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='users.UserAccount')),
            ],
            options={
                'db_table': 'identity',
            },
        ),
        migrations.CreateModel(
            name='MpesaIdentityVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_at', models.DateTimeField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Identity')),
                ('mpesa_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpesa.MpesaTransaction')),
            ],
            options={
                'db_table': 'mpesa_identity_verification',
            },
        ),
    ]
